#lang sicp
(define (double x)
  (* x 2))
(define (halve x)
  (/ x 2))
(define (mult x y)
  (define (iter x y a)
  (cond ((= y 0) a)
        ((= (remainder y 2) 0) (iter (double x) (halve y) a)) 
        (else (iter x (- y 1) (+ a x)))))
  (iter x y 0))